### ISSUE TITLE
Losing full screen when pressing shortcut key

### ISSUE THREAD

**Issue by stephenboston** [geeqie/geeqie.github.io#7]
I have a script that adds  the current image filename to a default collections file. There is no need for intervention or confirmation.

I have added this as a plugin and set a key to execute the plugin

Works great! Except: if I'm in full screen the action takes us out of full screen mode.

Is there a setting?

**Comment by caclark** [comment]
The feature is documented, but is hidden in order to confuse the users....
Go to `Help/On-Line Help Search` and type in `fullscreen`.
You should get a hit on `Plugins Configuration`.
The feature is `X-Geeqie-Keep-Fullscreen=true`.

This option, and others, is not included in the plugin template the user sees when creating a new plugin. I will fix that.

**Comment by caclark** [comment]
The plugin documentation is updated in https://github.com/BestImageViewer/geeqie/commit/844acecb1c885

**Comment by stephenboston** [comment]
Well hat went well. 

Thanks!
